### PR TITLE
fix: update docs with talos_version description

### LINKED ISSUE #196: setting version to v1.7.6 on machine config and secrets does not install talos 1.7.6
Hi,

Setting talos_version on machine config and secrets doesn't cause talos 1.7.6 to be installed.

Relevant terraform configuration

```
erraform {
  required_providers {
    # todo figure out how to  install 1.7.6 instead of 1.7.0 or 1.8.0-alpha.2
    talos = {
      source = "siderolabs/talos"
      version = "0.6.0-alpha.2"
    }
  }
}

provider "talos" {
  # Configuration options
}

resource "talos_machine_secrets" "this" {
  talos_version   = "v${var.talos_version}"
}

data "talos_machine_configuration" "controlplane" {
  talos_version    = "v${var.talos_version}"
  cluster_name     = var.cluster_name
  cluster_endpoint = var.cluster_endpoint
  machine_type     = "controlplane"
  machine_secrets  = talos_machine_secrets.this.machine_secrets
  config_patches   = [
    file("${path.root}/talos/machine-config-patch.yaml"),
    file("${path.root}/talos/control-plane-patch.yaml")
  ]
}

data "talos_machine_configuration" "worker" {
  talos_version    = "v${var.talos_version}"
  cluster_name     = var.cluster_name
  cluster_endpoint = var.cluster_endpoint
  machine_type     = "worker"
  machine_secrets  = talos_machine_secrets.this.machine_secrets
  config_patches   = [
    file("${path.root}/talos/machine-config-patch.yaml"),
  ]
}

data "talos_client_configuration" "this" {
  cluster_name         = var.cluster_name
  client_configuration = talos_machine_secrets.this.client_configuration
  endpoints            = [module.controlplane.ip_address]
}

resource "talos_machine_configuration_apply" "controlplane" {
  client_configuration        = talos_machine_secrets.this.client_configuration
  machine_configuration_input = data.talos_machine_configuration.controlplane.machine_configuration
  node                        = module.controlplane.ip_address
}

resource "talos_machine_configuration_apply" "worker" {
  client_configuration        = talos_machine_secrets.this.client_configuration
  machine_configuration_input = data.talos_machine_configuration.worker.machine_configuration
  node                        = module.worker.ip_address
}

resource "talos_machine_bootstrap" "this" {
  depends_on = [talos_machine_configuration_apply.controlplane]

  client_configuration = talos_machine_secrets.this.client_configuration
  node                 = module.controlplane.ip_address
}

resource "talos_cluster_kubeconfig" "this" {
  depends_on           = [talos_machine_bootstrap.this]
  client_configuration = talos_machine_secrets.this.client_configuration
  node                 = module.controlplane.ip_address
}
```

Tested on 0.5.0 and 0.6.0-alpha.2.  The former installs 1.7.0 and the latter always installs 1.8.0-alpha.2

### PR DESCRIPTION
**Pull request by NPastorale**
Update talos_version attribute description for clarity

Clarifies that the talos_version attribute controls Talos features and not the installed Talos version. Users should use config_patches to set the machine image version.

I also took the liberty of touching up the syntax a bit. Do let me know whether that's OK.

Fixes #196

### CODE REVIEW

File: pkg/talos/talos_machine_configuration_data_source.go [hunk 1]
```diff
@@ -90,7 +90,7 @@ func (d *talosMachineConfigurationDataSource) Schema(_ context.Context, _ dataso
 				Optional:    true,
 			},
 			"talos_version": schema.StringAttribute{
-				Description: "The version of talos features to use in generated machine configuration",
+				Description: "The version of talos features to use in the generated machine configuration. This does not control the installed Talos version. Use config_patches to set machine.install.image to the desired value",
```
Comment (smira) [inline pkg/talos/talos_machine_configuration_data_source.go]: We usually call it a "version contract", it doesn't have to be `v1.13.5`, just major + minor should be enough: `v1.13`. 

It should be set to the initial Talos version to be deployed, and never updated (otherwise the machine config might drift, as defaults would change).

**Review by smira — COMMENTED** [review]
Thanks for updating the docs, probably a minor clarification would help!

**Review by absurdlylongusername — CHANGES_REQUESTED** [review]
Thanks very much for making this change!

I'd appreciate also if the examples in the provider docs were updated to include `machine.install.image` patches for full clarity of how it should be done.

More specifically: 
- In the resource `talos_cluster_kubeconfig` example https://registry.terraform.io/providers/siderolabs/talos/0.11.0-beta.2/docs/resources/cluster_kubeconfig
- In the resource `talos_machine_bootstrap` example https://registry.terraform.io/providers/siderolabs/talos/0.11.0-beta.2/docs/data-sources/machine_configuration 
- In the resource `talos_machine_configuration_apply` example https://registry.terraform.io/providers/siderolabs/talos/0.11.0-beta.2/docs/resources/machine_configuration_apply
- In the data `talos_cluster_kubeconfig` example https://registry.terraform.io/providers/siderolabs/talos/0.11.0-beta.2/docs/data-sources/cluster_kubeconfig
- In the data `talos_machine_configuration` example https://registry.terraform.io/providers/siderolabs/talos/0.11.0-beta.2/docs/data-sources/machine_configuration

Also, I think the ephemeral version of the [`talos_machine_configuration`](https://registry.terraform.io/providers/siderolabs/talos/0.11.0-beta.2/docs/ephemeral-resources/machine_configuration) should have all the same information (including the example and the note about `talos_version`) that the [non-ephemeral version](https://registry.terraform.io/providers/siderolabs/talos/0.11.0-beta.2/docs/data-sources/machine_configuration) has

And the docs should also explicitly state the default behaviour of what version of talos is installed when you do not specify it  in config patches. This information should be included in the doc pages for `talos_machine_configuration` and `talos_machine_configuration_apply`

File: pkg/talos/talos_machine_configuration_data_source.go (hunk 1 above)
Comment (NPastorale) [reply pkg/talos/talos_machine_configuration_data_source.go]: I've changed the wording and added a few examples to reflect both the admission of major + minor, major + minor + patch (maybe not necessary?) and that it can be passed with or without a suffix v

**Comment by NPastorale** [comment]
I've tried to reconcile this the best I could. It is not my intention to pollute the docs with an overabundance of information either. I think this strikes a good balance, but I am open to ideas.

That said, I have also been biten by this before and it would have been nice to have some more information when starting.

Maybe the [contrib repo](https://github.com/siderolabs/contrib/tree/main/examples/terraform) could be mentioned as well, so more examples can be shown without making the Terraform docs too long?

**Comment by absurdlylongusername** [comment]
@NPastorale Thanks! This looks a lot better now.

The main reason I want the `machine.install.image` patch to be added to the kubeconfig examples is that the kube config part is basically "the end" of the talos initial setup workflow. Most of what happens afterwards is Kubernetes land.

So if a new person is coming to see how to setup their initial Talos kubernetes nodes on local machines, they'd want to see a simple straightforward step by step way of doing it that shows them what the expected structure should look like.

The [talos_cluster_kubeconfig](https://registry.terraform.io/providers/siderolabs/talos/0.11.0-beta.2/docs/data-sources/cluster_kubeconfig) example is about 85% of the way there, and the [contrib](https://github.com/siderolabs/contrib/tree/main/examples/terraform/basic) example is about 95% of the way there.

What is missing is how to replicate the expected result that you get when you follow the [get started guide](https://docs.siderolabs.com/talos/v1.12/getting-started/getting-started) from step 3 onwards (step 4 excluded).

If the 100% shouldn't be in the docs, then the docs should link to the [contrib repo](https://github.com/siderolabs/contrib/tree/main/examples/terraform/basic), and the contrib repo should be updated with information on:
- What `talos_version` actually does
- What default talos version actually ends up installed when you don't specify `machine.install.image`
- How to set the image version in the example provided

and the contrib example serves as the 100% getting started for Talos Terraform.

So that when I search `talos terraform`, and it comes back with the terraform provider and this repository as top 2 results, all the information that I need in order to set up an initial Talos kubernetes cluster locally is provided first class by Talos themselves, instead of in a github issue or someone's blog.

Also, I'd suggest that the [README](https://github.com/siderolabs/terraform-provider-talos/blob/main/README.md) be updated to point to the provider docs and the contrib repo as well.

And the contrib README only links to the cloud examples, but not the [basic](https://github.com/siderolabs/contrib/tree/main/examples/terraform/basic) example, so there's no easy way to know it exists without being told about it (same with all the other terraform examples not in the README).

Thoughts?
And should these be opened as issues on the relevant repos or is it enough that I've mentioned it here?

**Review by frezbo — APPROVED** [review]
